version: '2'
services:
  logic:
    build: ./logic
  depends_on:
    - filler
    - charger






  filler:
    build: ./filler





  charger:
    build: ./charger






  interface:
    build: "./interface"
    depends_on: 
      - logic
    ports:
      - "3000:80"