# Download composer, install dependencies, remove it
# apt-get install -y zip unzip git \
#   && curl https://getcomposer.org/installer --output composer-setup.php \
#   && php composer-setup.php \
#   && php composer.phar install \
#   && rm composer-setup.php composer.phar \
#   && apt-get remove -y zip unzip git \
#   && apt-get autoremove -y \
#   && apt-get clean \
#   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# /bin/bash -c <command to strart>
